name: Update Gallery Data
on:
  push:
    branches:
      - main  # Main branch'ine yapılan her push'ta çalışır
  workflow_dispatch: # Bu satır "Run workflow" butonunu ekler (Manuel çalıştırma)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/set-python@v4
        with:
          python-version: '3.9'

      - name: Generate JSON
        run: python generate_data.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data.json
          git commit -m "Automated data.json update" || exit 0
          git push
